apiVersion: v1
kind: Service
metadata:
  name: service-relicshop
spec:
  selector:
    app: service-relicshop
  type: NodePort
  ports:
    - name: http
      port: 8081
      nodePort: 31001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-relicshop
spec:
  selector:
    matchLabels:
      app: service-relicshop
  replicas: 1
  template:
    metadata:
      labels:
        app: service-relicshop
    spec:
      containers:
        - name: server
          image: denyaalpha/service-relicshop
          ports:
            - name: http
              containerPort: 8081

---